version: 2
updates:
  # npm依存関係の更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Node.js v22 LTSに固定するため、@types/nodeのメジャーバージョンアップを抑止
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  # GitHub Actions依存関係の更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
